from typing import Set

ROOM_POLYGON_LAYERS_CUSTOM_CLIENT_2: Set[str] = set()
WINDOW_LAYERS_CUSTOM_CLIENT_2 = {"A1E51_FENSTER"}
DOOR_LAYERS_CUSTOM_CLIENT_2 = {
    "A1E52_AUSSENTUEREN",
    "A1M16_INNENTUEREN",
}
KITCHEN_FEATURES_LAYERS_CUSTOM_CLIENT_2 = {"A1M61_EINBAUTEN"}
STAIRS_AND_RAMPS_FEATURES_LAYERS_CUSTOM_CLIENT_2 = {"A1E04_TREPPEN"}
SANITARY_FEATURES_LAYERS_CUSTOM_CLIENT_2 = {"A1I4_SANITAER"}
ELEVATOR_FEATURES_LAYERS_CUSTOM_CLIENT_2: Set[str] = set()

AREA_NAME_LAYER_CUSTOM_CLIENT_2 = "Z20_FM_STEMPEL"
WALL_LAYERS_HATCHES_CUSTOM_CLIENT_2 = {
    "31_AUSSENWAENDE_SCHRAFF",
    "32_INNENWAENDE_TR_SCHRAFF",
    "33_INNENWAENDE_NTR_SCHRAFF",
}
WALL_LAYERS_POLYLINES_CUSTOM_CLIENT_2 = {
    "E62_INNENWAENDE_NTR",
    "E61_INNENWAENDE_TRAGEND",
    "E41_AUSSENWAENDE",
}

RAILING_LAYERS_CUSTOM_CLIENT_2 = {"E03_BALKONE"}


LAYERS_INCLUDED_IN_IMAGE_CUSTOM_CLIENT_2 = {
    "0",
    "DEFPOINTS",
    "Z22_GF-POLYGONE",
    "A1UR_REFERENZ",
    "Z21_FM_RAUMATTRIBUTE",
    "0_RAUMSTEMPEL",
    "A1E04_TREPPEN",
    "E41_AUSSENWAENDE",
    "A1E51_FENSTER",
    "E61_INNENWAENDE_TRAGEND",
    "A1M16_INNENTUEREN",
    "E62_INNENWAENDE_NTR",
    "A1E52_AUSSENTUEREN",
    "A1M61_EINBAUTEN",
    "Z23_NGF-POLYGONE",
    "E03_BALKONE",
    "E40_BEMASSUNGEN_AUSSEN",
    "E60_BEMASSUNGEN_INNEN",
    "0_GF-STEMPEL",
    "A1I4_SANITAER",
    "A1XK_MASTER-PLANKOPF",
    "0_LUFTRAUM_HOHLRAUM",
    "0_STUETZENABZUGS-POLYGONE",
    "A1E1_DAECHER",
    "A1E56_FASSADEN",
    "A1E9_WAENDE",
    "A1I6_TRANSPORT",
    "A1M11_TRENNWAENDE",
    "A1M62_BRUESTUNGEN",
    "A1UJ_SCHNITTMARKEN",
    "A1VSZ_SCHRAFFUR-SOLID",
    "A1YA_ACHSEN",
    "A1Z260_RAUMSTEMPEL_EIN",
    "BWZ122_NGF-SCHRAFFUR",
    "BWZ122_NGF-SCHRAFFUR-MIETER",
    "BWZ122_NGF-SCHRAFFUR-MITNUTZUNG",
    "BWZ122_VMF-POLYGON",
    "BWZ122_VMF-SCHRAFFUR",
    "M00_ALLGEMEINES",
    "Raumstempel alt",
    "Z24_EBF-POLYGONE",
    "0_PLANRAND-VISIMOVE",
    "32_INNENWAENDE_TR_SCHRAFF",
    "31_AUSSENWAENDE_SCHRAFF",
    "Z22_AGF-POLYGONE",
    "Z23_ANGF-POLYGONE",
    "Z26_ABZUG_NGF",
    "Z26_ABZUG_GF",
    "Z26_ABZUG_ANGF",
    "Z26_ABZUG_AGF",
    "Z26_ABZUG_EBF",
    "Z20_FM_STEMPEL",
    "Z21_FM_ATTRIBUTE",
    "Z21_FM_ATTRIBUTE-SYS",
    "33_INNENWAENDE_NTR_SCHRAFF",
    "Z_BlockAlt",
    "Z27_NR_AGF",
    "Z27_NR_ANGF",
    "Z27_NR_EBF",
    "Z27_NR_GF",
    "Z27_NR_LUFT",
    "Z27_NR_NGF",
    "Z27_NR_VOLUMEN",
    "Z23_FM_NICHT_EBF",
    "A1E2_STUETZEN",
    "0_CADMEC_SCHRAFFUR",
    "0_KONSTRUKTION_OBEN",
    "0_KONSTRUKTION_UNTEN",
}

DOOR_BLOCK_NAME_PREFIXES_CUSTOM_CLIENT_2 = {"TUER"}
