ROOM_POLYGON_LAYERS_CUSTOM_CLIENT = {
    "Z22_NGF-POLYGONE",
    "Z23_ANGF-POLYGONE",
    "Z23_NGF-POLYGONE",
}
WINDOW_LAYERS_CUSTOM_CLIENT = {"E51_FENSTER"}
DOOR_LAYERS_CUSTOM_CLIENT = {
    "M16_INNENTUEREN",
    "E52_AUSSENTUEREN",
}
KITCHEN_FEATURES_LAYERS_CUSTOM_CLIENT = {"M72_KUECHEN"}
STAIRS_AND_RAMPS_FEATURES_LAYERS_CUSTOM_CLIENT = {"E04_TREPPEN_UND_RAMPEN"}
SANITARY_FEATURES_LAYERS_CUSTOM_CLIENT = {"P51_SANITAER"}
ELEVATOR_FEATURES_LAYERS_CUSTOM_CLIENT = {"I61_AUFZUEGE"}


AREA_NAME_LAYER_CUSTOM_CLIENT = "M0_ALLGEMEINES"
WALL_LAYERS_HATCHES_CUSTOM_CLIENT = {"0_SCHRAFFUR_INNEN", "0_SCHRAFFUR_AUSSEN"}
WALL_LAYERS_POLYLINES_CUSTOM_CLIENT = {
    "E62_INNENWAENDE_NICHTTR",
    "E61_INNENWAENDE_TRAGEND",
    "E41_AUSSENWAENDE_TRAGEND",
}
RAILING_LAYERS_CUSTOM_CLIENT = {"E03_BALKONE"}

LAYERS_INCLUDED_IN_IMAGE_CUSTOM_CLIENT = {
    "0_LEGENDE_MIETER",
    "B_RO_TEXT_2",
    "E03_BALKONE",
    "E04_TREPPEN_UND_RAMPEN",
    "E40_BEMASSUNGEN_AUSSEN",
    "E51_FENSTER",
    "E60_BEMASSUNGEN_INNEN",
    "E62_INNENWAENDE_NICHTTR",
    "E61_INNENWAENDE_TRAGEND",
    "E41_AUSSENWAENDE_TRAGEND",
    "I61_AUFZUEGE",
    "M0_ALLGEMEINES",
    "M16_INNENTUEREN",
    "M72_KUECHEN",
    "P51_SANITAER",
    "0_MASSSTAB",
    "0_NORDPFEIL",
    "0_PLANKOPF",
    "0_SCHRAFFUR_INNEN",
    "0_SCHRAFFUR_AUSSEN",
    "Z21_AGF-POLYGONE",
    "Z21_GF-POLYGONE",
    "Z22_ANF-POLYGONE",
    "Z22_NGF-POLYGONE",
}
