from enum import Enum

from brooks.constants import BathroomSubtype
from brooks.types import AreaType
from common_utils.constants import SUPPORTED_LANGUAGES


class LayoutLayers(Enum):
    DIMENSIONING = "DIMENSIONING"
    FEATURES = "FEATURES"
    RAILINGS = "RAILINGS"
    WALLS = "WALLS"
    WINDOWS = "WINDOWS"
    DOORS = "DOORS"
    ROOM_POLYGONS = "ROOM_POLYGONS"
    ROOM_STAMP = "ROOM_STAMP"
    TITLE_BLOCK = "TITLE_BLOCK"
    UNITS = "UNITS"
    SHAFTS = "SHAFTS"
    STAIRS_ELEVATORS = "STAIRS_AND_ELEVATORS"
    SANITARY_AND_KITCHEN = "SANITARY_AND_KITCHEN_ELEMENTS"


ROOM_VERBOSE_NAMES = {
    SUPPORTED_LANGUAGES.EN: {
        AreaType.ROOM: "Room",
        AreaType.BEDROOM: "Room",
        AreaType.LIVING_ROOM: "Room",
        AreaType.LIVING_DINING: "Living\nDining",
        AreaType.KITCHEN: "Kitchen",
        AreaType.KITCHEN_DINING: "Kitchen/\nDining",
        AreaType.BATHROOM: "Bath",
        AreaType.BALCONY: "Balcony",
        AreaType.LOGGIA: "Loggia",
        AreaType.CORRIDOR: "Corridor",
        AreaType.ELEVATOR: "Elevator",
        AreaType.STOREROOM: "Storage",
        AreaType.VOID: "Void",
        AreaType.DINING: "Room",
        AreaType.SHAFT: None,
        AreaType.WINTERGARTEN: "Wintergarden",
        AreaType.STAIRCASE: None,
        AreaType.LIGHTWELL: "Lightwell",
        # Special Bathroom types
        BathroomSubtype.WC: "WC",
        BathroomSubtype.SHOWER: "Shower",
        BathroomSubtype.LAUNDRY: "Bath",
        # Public Spaces
        AreaType.CARPARK: "Carpark",
        AreaType.BASEMENT_COMPARTMENT: "Basement",
        AreaType.BASEMENT: "Basement",
        AreaType.TECHNICAL_AREA: "Technical\nArea",
        AreaType.WASH_AND_DRY_ROOM: "Wash/Dry",
        AreaType.ARCADE: "Arcade",
        AreaType.BIKE_STORAGE: "Bikes",
        AreaType.PRAM_AND_BIKE_STORAGE_ROOM: "Prams/\nBikes",
        AreaType.GARDEN: "Garden",
        AreaType.OUTDOOR_VOID: "Outdoor\nVoid",
        AreaType.COMMUNITY_ROOM: "Community\nRoom",
        AreaType.BREAK_ROOM: "Break\nRoom",
        AreaType.WAITING_ROOM: "Waiting\nRoom",
        AreaType.CANTEEN: "Canteen",
        AreaType.PRISON_CELL: "Prison\nCell",
        AreaType.OFFICE_SPACE: "Office",
        AreaType.OFFICE: "Office",
        AreaType.OPEN_PLAN_OFFICE: "Open\nPlan\nOffice",
        AreaType.MEETING_ROOM: "Meeting\nRoom",
        AreaType.DESIGN_ROOM: "Design\nRoom",
        AreaType.COUNTER_ROOM: "Counter\nRoom",
        AreaType.CONTROL_ROOM: "Control\nRoom",
        AreaType.RECEPTION_ROOM: "Reception\nRoom",
        AreaType.OFFICE_TECH_ROOM: "Office\nTech\nRoom",
        AreaType.FACTORY_ROOM: "Factory\nRoom",
        AreaType.WORKSHOP: "Workshop",
        AreaType.TECHNICAL_LAB: "Technical\nLab",
        AreaType.PHYSICS_LAB: "Physics\nLab",
        AreaType.CHEMICAL_LAB: "Chemical\nLab",
        AreaType.LIVESTOCK: "Livestock",
        AreaType.PLANTS: "Plants",
        AreaType.COMMON_KITCHEN: "Kitchen",
        AreaType.SPECIAL_WORKSPACE: "Special\nWorkspace",
        AreaType.WAREHOUSE: "Warehouse",
        AreaType.ARCHIVE: "Archive",
        AreaType.COLD_STORAGE: "Cold\nStorage",
        AreaType.LOGISTICS: "Logistics",
        AreaType.SALESROOM: "Salesroom",
        AreaType.EXHIBITION: "Exhibition",
        AreaType.TEACHING_ROOM: "Teaching\nRoom",
        AreaType.FLEXIBLE_TEACHING_ROOM: "Flexible\nTeaching\nRoom",
        AreaType.DEDICATED_TEACHING_ROOM: "Dedicated\nTeaching\nRoom",
        AreaType.LIBRARY: "Library",
        AreaType.SPORTS_ROOMS: "Sports\nRooms",
        AreaType.ASSEMBLY_HALL: "Assembly\nHall",
        AreaType.STAGE_ROOM: "Stage\nRoom",
        AreaType.SHOWROOM: "Showroom",
        AreaType.CHAPEL: "Prayer Room",
        AreaType.MEDICAL_ROOM: "Medical\nRoom",
        AreaType.DEDICATED_MEDICAL_ROOM: "Dedicated\nMedical\nRoom",
        AreaType.SURGERY_ROOM: "Surgery\nRoom",
        AreaType.RADIATION_DIAGNOSIS: "Radiation\nDiagnosis",
        AreaType.RADATION_THERAPY: "Radation\nTherapy",
        AreaType.PHYSIO_AND_REHABILITATION: "Physio\nAnd\nRehabilitation",
        AreaType.MEDICAL_BEDROOM: "Medical\nBedroom",
        AreaType.DEDICATED_MEDICAL_BEDROOM: "Dedicated\nMedical\nBedroom",
        AreaType.SANITARY_ROOMS: "Sanitary\nRooms",
        AreaType.CLOAKROOM: "Cloakroom",
        AreaType.PASSENGER_PLATFORM: "Passenger\nPlatform",
        AreaType.HOUSE_TECHNICS_FACILITIES: "House\nTechnics\nFacilities",
        AreaType.SHELTER: "Shelter",
        AreaType.WASTEWATER: "Wastewater",
        AreaType.WATER_SUPPLY: "Water\nSupply",
        AreaType.HEATING: "Heating",
        AreaType.GAS: "Gas",
        AreaType.ELECTRICAL_SUPPLY: "Electrical\nSupply",
        AreaType.TELECOMMUNICATIONS: "Telecommunications",
        AreaType.AIR: "Air",
        AreaType.ELEVATOR_FACILITIES: "Elevator\nFacilities",
        AreaType.OPERATIONS_FACILITIES: "Operations\nRoom",
        AreaType.CORRIDORS_AND_HALLS: "Corridors\nAnd\nHalls",
        AreaType.TRANSPORT_SHAFT: "Transport\nShaft",
        AreaType.VEHICLE_TRAFFIC_AREA: "Vehicle\nTraffic\nArea",
        AreaType.FOYER: "Foyer",
        AreaType.LOBBY: "Lobby",
        AreaType.OIL_TANK: "Oil Tank",
        AreaType.PATIO: "Patio",
        AreaType.PRAM: "Pram Room",
        AreaType.STUDIO: "Studio",
        AreaType.TERRACE: "Terrace",
        AreaType.GARAGE: "Garage",
    },
    SUPPORTED_LANGUAGES.DE: {
        AreaType.ROOM: "Zimmer",
        AreaType.BEDROOM: "Zimmer",
        AreaType.LIVING_ROOM: "Wohnzimmer",
        AreaType.LIVING_DINING: "Wohnen\n/\nEssen",
        AreaType.KITCHEN: "Küche",
        AreaType.KITCHEN_DINING: "Küche\n/\nEssen",
        AreaType.BATHROOM: "Bad",
        AreaType.BALCONY: "Balkon",
        AreaType.LOGGIA: "Loggia",
        AreaType.CORRIDOR: "Flur",
        AreaType.ELEVATOR: "Aufzug",
        AreaType.STOREROOM: "Lagerraum",
        AreaType.VOID: "Luftraum",
        AreaType.DINING: "Zimmer",
        AreaType.SHAFT: None,
        AreaType.WINTERGARTEN: "Wintergarten",
        AreaType.STAIRCASE: None,
        AreaType.LIGHTWELL: "Lichtschacht",
        # Special Bathroom types
        BathroomSubtype.SHOWER: "Dusche",
        BathroomSubtype.WC: "WC",
        BathroomSubtype.LAUNDRY: "Bad",
        # Public Spaces
        AreaType.CARPARK: "Einstellhalle",
        AreaType.BASEMENT_COMPARTMENT: "Keller",
        AreaType.BASEMENT: "Keller",
        AreaType.TECHNICAL_AREA: "Technik",
        AreaType.WASH_AND_DRY_ROOM: "Waschen/Trocknen",
        AreaType.ARCADE: "Laubengang",
        AreaType.BIKE_STORAGE: "Fahrrad",
        AreaType.PRAM_AND_BIKE_STORAGE_ROOM: "Kinderwagen/Fahrrad",
        AreaType.GARDEN: "Garten",
        AreaType.OUTDOOR_VOID: "Aussenluftraum",
        AreaType.COMMUNITY_ROOM: "Gemeinschaftsraum",
        AreaType.BREAK_ROOM: "Pausenraum",
        AreaType.WAITING_ROOM: "Warteraum",
        AreaType.CANTEEN: "Speiseraum",
        AreaType.PRISON_CELL: "Haftraum",
        AreaType.OFFICE_SPACE: "Büroraum",
        AreaType.OFFICE: "Büroraum",
        AreaType.OPEN_PLAN_OFFICE: "Grossraumbüros",
        AreaType.MEETING_ROOM: "Besprechungsraum",
        AreaType.DESIGN_ROOM: "Konstruktionsraum",
        AreaType.COUNTER_ROOM: "Schalterraum",
        AreaType.CONTROL_ROOM: "Bedienungsraum",
        AreaType.RECEPTION_ROOM: "Aufstichtsraum",
        AreaType.OFFICE_TECH_ROOM: "Bürotechnikraum",
        AreaType.FACTORY_ROOM: "Werkhallen",
        AreaType.WORKSHOP: "Werkstätten",
        AreaType.TECHNICAL_LAB: "Technologische\nLabors",
        AreaType.PHYSICS_LAB: "Physikalische, physika-\nlisch-technische, elektro-\ntechnische\nLabors",
        AreaType.CHEMICAL_LAB: "Chemische, bakteriologi-\nsche, morphologische\nLa-\nbors",
        AreaType.LIVESTOCK: "Raum\nfür\nTierhaltung",
        AreaType.PLANTS: "Raum\nfür\nPflanzenzucht",
        AreaType.COMMON_KITCHEN: "Küchen",
        AreaType.SPECIAL_WORKSPACE: "Sonderarbeitsraum",
        AreaType.WAREHOUSE: "Lagerraum",
        AreaType.ARCHIVE: "Archive, Sammlungsraum",
        AreaType.COLD_STORAGE: "Kühlraum",
        AreaType.LOGISTICS: "Annahme- und\nAbgaberaum",
        AreaType.SALESROOM: "Verkaufsraum",
        AreaType.EXHIBITION: "Ausstellungsraum",
        AreaType.TEACHING_ROOM: "Unterrichtsraum\nmit\nfestem\nGestühl",
        AreaType.FLEXIBLE_TEACHING_ROOM: "Allg. Unterrichts- und\nÜbungsraum\nohne festes Gestühl",
        AreaType.DEDICATED_TEACHING_ROOM: "Bes. Unterrichtsraum\nohne\nfestes Gestühl",
        AreaType.LIBRARY: "Bibliotheksraum",
        AreaType.SPORTS_ROOMS: "Sportraum",
        AreaType.ASSEMBLY_HALL: "Versammlungsraum",
        AreaType.STAGE_ROOM: "Bühnen-, Studioraum",
        AreaType.SHOWROOM: "Schauraum",
        AreaType.CHAPEL: "Gebetsraum",
        AreaType.MEDICAL_ROOM: "Raum\nmit\nallg. med. Auststatt.",
        AreaType.DEDICATED_MEDICAL_ROOM: "Raum\nm. bes. med. Ausstatt.",
        AreaType.SURGERY_ROOM: "Operationsraum",
        AreaType.RADIATION_DIAGNOSIS: "Raum\nfür\nStrahlendiagnose",
        AreaType.RADATION_THERAPY: "Raum\nfür\nStrahlentherapie",
        AreaType.PHYSIO_AND_REHABILITATION: "Raum\nfür\nPhysio",
        AreaType.MEDICAL_BEDROOM: "Bettenraum",
        AreaType.DEDICATED_MEDICAL_BEDROOM: "Bettenraum\nmit\nbes. Ausstattung",
        AreaType.SANITARY_ROOMS: "Sanitärraum",
        AreaType.CLOAKROOM: "Garderoben",
        AreaType.PASSENGER_PLATFORM: "Fahrgastflächen",
        AreaType.HOUSE_TECHNICS_FACILITIES: "Raum\nfür\nzentrale\nTechnik",
        AreaType.SHELTER: "Schutzraum",
        AreaType.WASTEWATER: "Abwasseraufb. u. -beseitigung",
        AreaType.WATER_SUPPLY: "Wasserversorgung",
        AreaType.HEATING: "Heizung- u. Brauchwassererwärm.",
        AreaType.GAS: "Gase\nu. Flüssigkeiten",
        AreaType.ELECTRICAL_SUPPLY: "Elektrische\nStromversorgung",
        AreaType.TELECOMMUNICATIONS: "Fernmeldetechnik",
        AreaType.AIR: "Raumlufttechn. Anlagen",
        AreaType.ELEVATOR_FACILITIES: "Aufzugs. und\nFörderanlagen",
        AreaType.OPERATIONS_FACILITIES: "Betriebstechn. Anlagen",
        AreaType.CORRIDORS_AND_HALLS: "Flure\n/Hallen",
        AreaType.TRANSPORT_SHAFT: "Schächte\nfür\nFörderungsanlagen",
        AreaType.VEHICLE_TRAFFIC_AREA: "Fahrzeugverkehrsfläche",
        AreaType.FOYER: "Foyer",
        AreaType.LOBBY: "Eingang",
        AreaType.OIL_TANK: "Öltank",
        AreaType.PATIO: "Innenhof",
        AreaType.PRAM: "Kinderwagen",
        AreaType.STUDIO: "Studio",
        AreaType.TERRACE: "Terrasse",
        AreaType.GARAGE: "Garage",
    },
    SUPPORTED_LANGUAGES.FR: {
        AreaType.ROOM: "Chambre",
        AreaType.BEDROOM: "Chambre",
        AreaType.LIVING_ROOM: "Chambre",
        AreaType.LIVING_DINING: "Salon\n/\nManger",
        AreaType.KITCHEN: "Cuisine",
        AreaType.KITCHEN_DINING: "Cuisine\n/\nManger",
        AreaType.BATHROOM: "Bains",
        AreaType.BALCONY: "Balcon",
        AreaType.LOGGIA: "Loggia",
        AreaType.CORRIDOR: "Couloir",
        AreaType.ELEVATOR: "Ascenseur",
        AreaType.STOREROOM: "Stockage",
        AreaType.VOID: "Espace",
        AreaType.DINING: "Chambre",
        AreaType.SHAFT: None,
        AreaType.WINTERGARTEN: "Jardin\nd'hiver",
        AreaType.STAIRCASE: None,
        AreaType.LIGHTWELL: "Puits\nde lumiere",
        # Special Bathroom types
        BathroomSubtype.SHOWER: "Douche",
        BathroomSubtype.WC: "WC",
        BathroomSubtype.LAUNDRY: "Bains",
        # Public Spaces
        AreaType.CARPARK: "Parking",
        AreaType.BASEMENT_COMPARTMENT: "Sous-sol",
        AreaType.BASEMENT: "Sous-sol",
        AreaType.TECHNICAL_AREA: "Domaine\nTechnique",
        AreaType.WASH_AND_DRY_ROOM: "Lavage\net\nséchage",
        AreaType.ARCADE: "Arcade",
        AreaType.BIKE_STORAGE: "Vélos",
        AreaType.PRAM_AND_BIKE_STORAGE_ROOM: "Landau/Vélo",
        AreaType.GARDEN: "Jardin",
        AreaType.OUTDOOR_VOID: "Espace\nen\nplein\nair",
        AreaType.COMMUNITY_ROOM: "Salle\ncommunautaire",
        AreaType.BREAK_ROOM: "Salle\nde pause",
        AreaType.WAITING_ROOM: "Salle\nd'attente",
        AreaType.CANTEEN: "Cantine",
        AreaType.PRISON_CELL: "Cellule\nde prison",
        AreaType.OFFICE_SPACE: "Bureau",
        AreaType.OFFICE: "Bureau",
        AreaType.OPEN_PLAN_OFFICE: "Bureau\nouverts",
        AreaType.MEETING_ROOM: "Salle\nde réunion",
        AreaType.DESIGN_ROOM: "Salle\nde conception",
        AreaType.COUNTER_ROOM: "Salle\ncontre\nle compteur",
        AreaType.CONTROL_ROOM: "Salle\nde contrôle",
        AreaType.RECEPTION_ROOM: "Salle\nde réception",
        AreaType.OFFICE_TECH_ROOM: "Chambre\nTech\nOffice",
        AreaType.FACTORY_ROOM: "Salle\nd'usine",
        AreaType.WORKSHOP: "Atelier",
        AreaType.TECHNICAL_LAB: "Laboratoire\ntechnique",
        AreaType.PHYSICS_LAB: "Laboratoire\nde physique",
        AreaType.CHEMICAL_LAB: "Laboratoire\nchimique",
        AreaType.LIVESTOCK: "Bétail",
        AreaType.PLANTS: "Les\nplantes",
        AreaType.COMMON_KITCHEN: "Cuisine",
        AreaType.SPECIAL_WORKSPACE: "Espace\nde travail\nspécial",
        AreaType.WAREHOUSE: "Entrepôt",
        AreaType.ARCHIVE: "Archiver",
        AreaType.COLD_STORAGE: "Chambre\nfroide",
        AreaType.LOGISTICS: "Logistique",
        AreaType.SALESROOM: "Salle\nde vente",
        AreaType.EXHIBITION: "Exposition",
        AreaType.TEACHING_ROOM: "Salle\nd'enseignement",
        AreaType.FLEXIBLE_TEACHING_ROOM: "Salle\nd'enseignement\nflexible",
        AreaType.DEDICATED_TEACHING_ROOM: "Salle\nd'enseignement\ndédié",
        AreaType.LIBRARY: "Bibliothèque",
        AreaType.SPORTS_ROOMS: "Chambres\nde sport",
        AreaType.ASSEMBLY_HALL: "Salle\nde réunion",
        AreaType.STAGE_ROOM: "Salle\nde scène",
        AreaType.SHOWROOM: "Salle\nd'exposition",
        AreaType.CHAPEL: "salle\nde\nprière",
        AreaType.MEDICAL_ROOM: "Salle\nmédicale",
        AreaType.DEDICATED_MEDICAL_ROOM: "Salle\nmédicale\ndédiée",
        AreaType.SURGERY_ROOM: "Salle\nd'opération",
        AreaType.RADIATION_DIAGNOSIS: "Diagnostic\nradiologique",
        AreaType.RADATION_THERAPY: "Thérapie\nde radation",
        AreaType.PHYSIO_AND_REHABILITATION: "Physio\net\nréhabilitation",
        AreaType.MEDICAL_BEDROOM: "Chambre\nmédicale",
        AreaType.DEDICATED_MEDICAL_BEDROOM: "Chambre\nà coucher\nmédicale\ndédiée",
        AreaType.SANITARY_ROOMS: "Chambres\nsanitaires",
        AreaType.CLOAKROOM: "Vestiaire",
        AreaType.PASSENGER_PLATFORM: "Plate-forme\nde passager",
        AreaType.HOUSE_TECHNICS_FACILITIES: "Equipement\nde la\ntechnique de la maison",
        AreaType.SHELTER: "Abri",
        AreaType.WASTEWATER: "les\neaux\nusées",
        AreaType.WATER_SUPPLY: "Approvisionnement\nen\neau",
        AreaType.HEATING: "Chauffage",
        AreaType.GAS: "Gaz",
        AreaType.ELECTRICAL_SUPPLY: "Fourniture\nélectrique",
        AreaType.TELECOMMUNICATIONS: "Télécommunications",
        AreaType.AIR: "Air",
        AreaType.ELEVATOR_FACILITIES: "Installations\nd'ascenseur",
        AreaType.OPERATIONS_FACILITIES: "Salle\nd'opérations",
        AreaType.CORRIDORS_AND_HALLS: "Corridors\net\nhalls",
        AreaType.TRANSPORT_SHAFT: "Arbre\nde transport",
        AreaType.VEHICLE_TRAFFIC_AREA: "Zone\nde circulation\ndu véhicule",
        AreaType.FOYER: "Foyer",
        AreaType.LOBBY: "Hall",
        AreaType.OIL_TANK: "Cuve\nà mazout",
        AreaType.PATIO: "Patio",
        AreaType.PRAM: "Lambeau",
        AreaType.STUDIO: "Studio",
        AreaType.TERRACE: "Terrasse",
        AreaType.GARAGE: "Garage",
    },
    SUPPORTED_LANGUAGES.IT: {
        AreaType.ROOM: "Camera",
        AreaType.BEDROOM: "Camera",
        AreaType.LIVING_ROOM: "Camera",
        AreaType.LIVING_DINING: "Soggiorno/\nMangia",
        AreaType.KITCHEN: "Cucina",
        AreaType.KITCHEN_DINING: "Cucina/\nMangia",
        AreaType.BATHROOM: "Bagno",
        AreaType.BALCONY: "Balcone",
        AreaType.LOGGIA: "Loggia",
        AreaType.CORRIDOR: "Corridoio",
        AreaType.ELEVATOR: "Ascensore",
        AreaType.STOREROOM: "Stockage",
        AreaType.VOID: "Pozzo\nluce",
        AreaType.DINING: "Camera",
        AreaType.SHAFT: None,
        AreaType.WINTERGARTEN: "Giardino\nd'inverno",
        AreaType.STAIRCASE: None,
        AreaType.LIGHTWELL: "Pozzo\nluce",
        # Special Bathroom types
        BathroomSubtype.SHOWER: "Doccia",
        BathroomSubtype.WC: "WC",
        BathroomSubtype.LAUNDRY: "Bagno",
        # Public Spaces
        AreaType.CARPARK: "Parcheggio",
        AreaType.BASEMENT_COMPARTMENT: "Seminterrato",
        AreaType.BASEMENT: "Seminterrato",
        AreaType.TECHNICAL_AREA: "Area\ntecnica",
        AreaType.WASH_AND_DRY_ROOM: "Lavaggio\ne\nasciugatura",
        AreaType.ARCADE: "Arcade",
        AreaType.BIKE_STORAGE: "Bici",
        AreaType.PRAM_AND_BIKE_STORAGE_ROOM: "Carrozzina/Bici",
        AreaType.GARDEN: "Giardino",
        AreaType.OUTDOOR_VOID: "Pozzo\nluce\nall'aperto",
        AreaType.COMMUNITY_ROOM: "Camera\ncomunitaria",
        AreaType.BREAK_ROOM: "Stanza\ndi\nristoro",
        AreaType.WAITING_ROOM: "Sala\nD'Attesa",
        AreaType.CANTEEN: "Mensa",
        AreaType.PRISON_CELL: "Cella\ndi\nprigione",
        AreaType.OFFICE_SPACE: "Ufficio",
        AreaType.OFFICE: "Ufficio",
        AreaType.OPEN_PLAN_OFFICE: "Ufficio\nopen\nspace",
        AreaType.MEETING_ROOM: "Sala\nriunioni",
        AreaType.DESIGN_ROOM: "Design\nroom.",
        AreaType.COUNTER_ROOM: "Contatore",
        AreaType.CONTROL_ROOM: "Sala\ndi\ncontrollo",
        AreaType.RECEPTION_ROOM: "Reception",
        AreaType.OFFICE_TECH_ROOM: "Camera\ntecnica\nper\nufficio.",
        AreaType.FACTORY_ROOM: "Camera\ndella\nfabbrica",
        AreaType.WORKSHOP: "Workshop.",
        AreaType.TECHNICAL_LAB: "Laboratorio\ntecnico",
        AreaType.PHYSICS_LAB: "Laboratorio\ndi\nfisica",
        AreaType.CHEMICAL_LAB: "Laboratorio\nchimico",
        AreaType.LIVESTOCK: "Bestiame",
        AreaType.PLANTS: "Impianti",
        AreaType.COMMON_KITCHEN: "Cucina",
        AreaType.SPECIAL_WORKSPACE: "Spazio\ndi\nlavoro\nspeciali",
        AreaType.WAREHOUSE: "Magazzino",
        AreaType.ARCHIVE: "Archivio",
        AreaType.COLD_STORAGE: "Celle\nfrigorifere",
        AreaType.LOGISTICS: "la\nlogistica",
        AreaType.SALESROOM: "Salesroom.",
        AreaType.EXHIBITION: "Esposizione",
        AreaType.TEACHING_ROOM: "Sala\ndidattica",
        AreaType.FLEXIBLE_TEACHING_ROOM: "Sala\ndidattica\nflessibile",
        AreaType.DEDICATED_TEACHING_ROOM: "Sala\ndidattica\ndedicata",
        AreaType.LIBRARY: "Biblioteca",
        AreaType.SPORTS_ROOMS: "Camere\nsportive",
        AreaType.ASSEMBLY_HALL: "Hall\nAssembly.",
        AreaType.STAGE_ROOM: "Stage\nRoom.",
        AreaType.SHOWROOM: "Showroom",
        AreaType.CHAPEL: "stanza\ndi\npreghiera",
        AreaType.MEDICAL_ROOM: "Stanza\nmedica",
        AreaType.DEDICATED_MEDICAL_ROOM: "Sala\nmedica\ndedicata",
        AreaType.SURGERY_ROOM: "Sala\noperatoria",
        AreaType.RADIATION_DIAGNOSIS: "Diagnosi\ndelle\nradiazioni.",
        AreaType.RADATION_THERAPY: "Terapia\nradurata",
        AreaType.PHYSIO_AND_REHABILITATION: "Fisio\ne\nriabilitazione",
        AreaType.MEDICAL_BEDROOM: "Camera\nda\nletto\nmedica",
        AreaType.DEDICATED_MEDICAL_BEDROOM: "Camera\nda\nletto\nmedica dedicata",
        AreaType.SANITARY_ROOMS: "Camere\nsanitarie",
        AreaType.CLOAKROOM: "Guardaroba",
        AreaType.PASSENGER_PLATFORM: "Piattaforma\npasseggeri",
        AreaType.HOUSE_TECHNICS_FACILITIES: "Casa\nTechnics\nStrutture",
        AreaType.SHELTER: "Riparo",
        AreaType.WASTEWATER: "Acque\nreflue",
        AreaType.WATER_SUPPLY: "Fornitura\nd'acqua",
        AreaType.HEATING: "Il\nriscaldamento",
        AreaType.GAS: "Gas",
        AreaType.ELECTRICAL_SUPPLY: "Fornitura\nelettrica",
        AreaType.TELECOMMUNICATIONS: "Telecomunicazioni",
        AreaType.AIR: "Aria",
        AreaType.ELEVATOR_FACILITIES: "Ascensore\nStrutture.",
        AreaType.OPERATIONS_FACILITIES: "Camera\noperativa",
        AreaType.CORRIDORS_AND_HALLS: "Corridoi\ne\nsale",
        AreaType.TRANSPORT_SHAFT: "Albero\ndi\ntrasporto",
        AreaType.VEHICLE_TRAFFIC_AREA: "Area\ndel\ntraffico\ndel veicolo",
        AreaType.FOYER: "Foyer",
        AreaType.LOBBY: "Atrio",
        AreaType.OIL_TANK: "Serbatoio\ndell'olio",
        AreaType.PATIO: "Patio",
        AreaType.PRAM: "Sala\ndel carrozzina",
        AreaType.STUDIO: "Studio",
        AreaType.TERRACE: "Terrazza",
        AreaType.GARAGE: "Garage",
    },
}
