module.exports = {
  lon: 8.53,
  lat: 47.36,
  basic_features_error: {
    errors: [null],
  },
  basic_features_status: 'UNPROCESSED',
  calibrator_config: [],
  classification_scheme: 'Archilyse',
  client_id: 63,
  client_site_id: 'some_client_site_id',
  created: '2020-07-17T09:19:00.476302',
  currently_assigned: false,
  delivered: false,
  full_slam_results: 'UNPROCESSED',
  gcs_3d_model_link: null,
  gcs_buildings_link: 'https://mock-link',
  gcs_ifc_link: null,
  gcs_json_surroundings_link: null,
  group_id: null,
  heatmaps_qa_complete: false,
  id: 1455,
  name: 'Office building',
  pipeline_and_qa_complete: false,
  priority: 10,
  raw_dir: '',
  region: 'Gotham',
  site_plan_file: null,
  updated: '2020-07-17T09:21:15.242467',
  validation_notes: null,
};
