from common_utils.constants import SurroundingType

DEFAULT_STREET_WIDTH = 6  # meters
DEFAULT_RIVER_WIDTH = 2
DEFAULT_RAILWAY_WIDTH = 1
DEFAULT_TREE_HEIGHT = 8

# Buffers to remove surroundings
SAFETY_BUFFER_BY_SURROUNDING_TYPE = {SurroundingType.BUILDINGS: 2.5}
DEFAULT_SAFETY_BUFFER = 0.1

MOUNTAINS_RESOLUTION = 300
BOUNDING_BOX_EXTENSION_SMALL_ITEMS: int = 500
BOUNDING_BOX_EXTENSION_BIG_ITEMS: int = 5000
