from brooks.types import AreaType
from handlers.dxf.dxf_constants_per_client.dxf_constants_custom_client import (
    AREA_NAME_LAYER_CUSTOM_CLIENT,
    DOOR_LAYERS_CUSTOM_CLIENT,
    ELEVATOR_FEATURES_LAYERS_CUSTOM_CLIENT,
    KITCHEN_FEATURES_LAYERS_CUSTOM_CLIENT,
    LAYERS_INCLUDED_IN_IMAGE_CUSTOM_CLIENT,
    RAILING_LAYERS_CUSTOM_CLIENT,
    ROOM_POLYGON_LAYERS_CUSTOM_CLIENT,
    SANITARY_FEATURES_LAYERS_CUSTOM_CLIENT,
    STAIRS_AND_RAMPS_FEATURES_LAYERS_CUSTOM_CLIENT,
    WALL_LAYERS_HATCHES_CUSTOM_CLIENT,
    WALL_LAYERS_POLYLINES_CUSTOM_CLIENT,
    WINDOW_LAYERS_CUSTOM_CLIENT,
)
from handlers.dxf.dxf_constants_per_client.dxf_constants_custom_client_2 import (
    AREA_NAME_LAYER_CUSTOM_CLIENT_2,
    DOOR_BLOCK_NAME_PREFIXES_CUSTOM_CLIENT_2,
    DOOR_LAYERS_CUSTOM_CLIENT_2,
    ELEVATOR_FEATURES_LAYERS_CUSTOM_CLIENT_2,
    KITCHEN_FEATURES_LAYERS_CUSTOM_CLIENT_2,
    LAYERS_INCLUDED_IN_IMAGE_CUSTOM_CLIENT_2,
    RAILING_LAYERS_CUSTOM_CLIENT_2,
    ROOM_POLYGON_LAYERS_CUSTOM_CLIENT_2,
    SANITARY_FEATURES_LAYERS_CUSTOM_CLIENT_2,
    STAIRS_AND_RAMPS_FEATURES_LAYERS_CUSTOM_CLIENT_2,
    WALL_LAYERS_HATCHES_CUSTOM_CLIENT_2,
    WALL_LAYERS_POLYLINES_CUSTOM_CLIENT_2,
    WINDOW_LAYERS_CUSTOM_CLIENT_2,
)
from handlers.editor_v2.schema import ReactPlannerName

ROOM_POLYGON_LAYERS = (
    ROOM_POLYGON_LAYERS_CUSTOM_CLIENT | ROOM_POLYGON_LAYERS_CUSTOM_CLIENT_2
)
WINDOW_LAYERS = WINDOW_LAYERS_CUSTOM_CLIENT | WINDOW_LAYERS_CUSTOM_CLIENT_2
DOOR_LAYERS = DOOR_LAYERS_CUSTOM_CLIENT | DOOR_LAYERS_CUSTOM_CLIENT_2
KITCHEN_FEATURES_LAYERS = (
    KITCHEN_FEATURES_LAYERS_CUSTOM_CLIENT | KITCHEN_FEATURES_LAYERS_CUSTOM_CLIENT_2
)
STAIRS_AND_RAMPS_FEATURES_LAYERS = (
    STAIRS_AND_RAMPS_FEATURES_LAYERS_CUSTOM_CLIENT
    | STAIRS_AND_RAMPS_FEATURES_LAYERS_CUSTOM_CLIENT_2
)
SANITARY_FEATURES_LAYERS = (
    SANITARY_FEATURES_LAYERS_CUSTOM_CLIENT | SANITARY_FEATURES_LAYERS_CUSTOM_CLIENT_2
)
ELEVATOR_FEATURES_LAYERS = (
    ELEVATOR_FEATURES_LAYERS_CUSTOM_CLIENT | ELEVATOR_FEATURES_LAYERS_CUSTOM_CLIENT_2
)
DOOR_BLOCK_NAME_PREFIXES = DOOR_BLOCK_NAME_PREFIXES_CUSTOM_CLIENT_2


AREA_NAME_LAYER = {
    AREA_NAME_LAYER_CUSTOM_CLIENT,
    AREA_NAME_LAYER_CUSTOM_CLIENT_2,
    "ALLGEMEINES",
}
AREA_NAME_ENTITY_TYPE = "TEXT"
WALL_LAYERS_HATCHES = (
    WALL_LAYERS_HATCHES_CUSTOM_CLIENT | WALL_LAYERS_HATCHES_CUSTOM_CLIENT_2
)
WALL_LAYERS_POLYLINES = (
    WALL_LAYERS_POLYLINES_CUSTOM_CLIENT | WALL_LAYERS_POLYLINES_CUSTOM_CLIENT_2
)
RAILING_LAYERS = RAILING_LAYERS_CUSTOM_CLIENT | RAILING_LAYERS_CUSTOM_CLIENT_2

ARC_DEGREE_PER_POINT = (
    0.01  # The smaller this value the more dense the points are created along the arc
)

BUFFER_LINES_OF_ELEVATOR_GEOMETRIES = (
    0.1  # corresponds to 0.1 cm as we assume the dxf geometries are provided in cm
)
ELEVATOR_MINIMUM_DIMENSION = 50

LAYERS_INCLUDED_IN_IMAGE = (
    LAYERS_INCLUDED_IN_IMAGE_CUSTOM_CLIENT | LAYERS_INCLUDED_IN_IMAGE_CUSTOM_CLIENT_2
)

SNAP_DOOR_TO_WALL_THRESHOLD_IN_CM = 1
OPENING_DISCARDING_AREA_THRESHOLD_IN_CM_2 = 100
BUFFER_DOOR_WINDOW_DIFFERENCE_IN_CM = 0.0001
NEGLECTABLE_SKELETON_LINE_LENGTH_IN_CM = 0.001
NEGLECTABLE_SKELETON_LINE_WIDTH_IN_CM = 0.001
RAILING_DEFAULT_WIDTH_IN_CM = 10
WALL_DEFAULT_WIDTH_IN_CM = 5
POLYGON_DUPLICATED_THRESHOLD_IN_CM2 = 1000
POLYGON_DUPLICATED_THRESHOLD_IN_PERCENTAGE = 0.8
DISTANCE_TO_DISCARD_DOOR_ARC_LINES_ASSOCIATION = 10**-3
KITCHEN_MINIMUM_SIDE_LENGTH = 30
DISTANCE_TO_GROUP_STAIRS = 100
MINIMUM_PERCENTAGE_AREA_ADDITION_TO_NOT_BE_REMOVED = 10
AREA_IS_SHAFT_THRESHOLD_IN_M2 = 1.0
CUSTOM_CLIENT_LETTER_SIGNATURE_FOR_IN_BETWEEN_FLOORS = "F"
MINIMUM_WINDOW_SIZE_IN_CM2 = 0.1


LAYER_KEYWORDS = {
    ReactPlannerName.ENTRANCE_DOOR: {},
    ReactPlannerName.DOOR: {"TUER", "EINGANG", *DOOR_LAYERS},
    ReactPlannerName.SLIDING_DOOR: {},
    ReactPlannerName.WINDOW: {"FENSTER", *WINDOW_LAYERS},
    ReactPlannerName.AREA_SPLITTER: {},
    ReactPlannerName.COLUMN: {"SAEULE"},
    ReactPlannerName.RAILING: {"GELAENDER", *RAILING_LAYERS},
    ReactPlannerName.WALL: {"WAENDE", *WALL_LAYERS_POLYLINES},
    ReactPlannerName.KITCHEN: {"KUECHE", *KITCHEN_FEATURES_LAYERS},
    ReactPlannerName.SEAT: {},
    ReactPlannerName.SHOWER: {"SANITAER", *SANITARY_FEATURES_LAYERS},
    ReactPlannerName.STAIRS: {"TREPPE", *STAIRS_AND_RAMPS_FEATURES_LAYERS},
    ReactPlannerName.TOILET: {"SANITAER", *SANITARY_FEATURES_LAYERS},
    ReactPlannerName.CAR_PARKING: {},
    ReactPlannerName.ELEVATOR: {"AUFZUG", *ELEVATOR_FEATURES_LAYERS},
    ReactPlannerName.BATHTUB: {"SANITAER", *SANITARY_FEATURES_LAYERS},
    ReactPlannerName.RAMP: {"RAMPE", *STAIRS_AND_RAMPS_FEATURES_LAYERS},
    ReactPlannerName.SINK: {"SANITAER", *SANITARY_FEATURES_LAYERS},
    ReactPlannerName.BUILT_IN_FURNITURE: {},
    ReactPlannerName.BIKE_PARKING: {},
    ReactPlannerName.SHAFT: {},
    ReactPlannerName.WASHING_MACHINE: {},
    ReactPlannerName.OFFICE_DESK: {},
    ReactPlannerName.VERTEX: {},
    ReactPlannerName.AREA: {"NGF", *ROOM_POLYGON_LAYERS},
}

BLOCK_KEYWORDS = {
    ReactPlannerName.ENTRANCE_DOOR: {},
    ReactPlannerName.DOOR: {"TUER", *DOOR_BLOCK_NAME_PREFIXES},
    ReactPlannerName.SLIDING_DOOR: {},
    ReactPlannerName.WINDOW: {"FENSTER"},
    ReactPlannerName.AREA_SPLITTER: {},
    ReactPlannerName.COLUMN: {},
    ReactPlannerName.RAILING: {},
    ReactPlannerName.WALL: {},
    ReactPlannerName.KITCHEN: {},
    ReactPlannerName.SEAT: {},
    ReactPlannerName.SHOWER: {"DU"},
    ReactPlannerName.STAIRS: {},
    ReactPlannerName.TOILET: {"WC"},
    ReactPlannerName.CAR_PARKING: {},
    ReactPlannerName.ELEVATOR: {},
    ReactPlannerName.BATHTUB: {"BW"},
    ReactPlannerName.RAMP: {},
    ReactPlannerName.SINK: {"WB"},
    ReactPlannerName.BUILT_IN_FURNITURE: {},
    ReactPlannerName.BIKE_PARKING: {},
    ReactPlannerName.SHAFT: {},
    ReactPlannerName.WASHING_MACHINE: {},
    ReactPlannerName.OFFICE_DESK: {},
    ReactPlannerName.VERTEX: {},
    ReactPlannerName.AREA: {},
}


AREA_NAME_TO_TYPE_MAPPING = {
    "ZIMMER": AreaType.ROOM,
    "WOHNEN": AreaType.LIVING_ROOM,
    "BALKON": AreaType.BALCONY,
    "BALCONE": AreaType.BALCONY,
    "BALCON": AreaType.BALCONY,
    "TERRASSE": AreaType.TERRACE,
    "KELLER": AreaType.BASEMENT,
    "SCHLAFEN": AreaType.ROOM,
    "KIND": AreaType.ROOM,
    "ENFANTS": AreaType.ROOM,
    "ENFANT": AreaType.ROOM,
    "CAMERA": AreaType.ROOM,
    "ELTERN": AreaType.ROOM,
    "PARENTS": AreaType.ROOM,
    "CHAMBRE": AreaType.ROOM,
    "DORMIRE": AreaType.ROOM,
    "SITZPLATZ": AreaType.TERRACE,
    "WASCHEN": AreaType.WASH_AND_DRY_ROOM,
    "TROCKNEN": AreaType.WASH_AND_DRY_ROOM,
    "TROCKENRAUM": AreaType.WASH_AND_DRY_ROOM,
    "LOGGIA": AreaType.LOGGIA,
    "LAGER": AreaType.WAREHOUSE,
    "TECHNIK": AreaType.HOUSE_TECHNICS_FACILITIES,
    "WOHNENESSEN": AreaType.LIVING_DINING,
    "ESSEN": AreaType.KITCHEN,
    "VELO": AreaType.BIKE_STORAGE,
    "VELOS": AreaType.BIKE_STORAGE,
    "VELORAUM": AreaType.BIKE_STORAGE,
    "HAUSTECHNIK": AreaType.TECHNICAL_AREA,
    "SCHUTZRAUM": AreaType.SHELTER,
    "BUERO": AreaType.OFFICE,
    "BUREAU": AreaType.OFFICE,
    "HEIZUNG": AreaType.HEATING,
    "GARAGE": AreaType.GARAGE,
    "LUFTRAUM": AreaType.LIGHTWELL,
    "LUFT": AreaType.LIGHTWELL,
    "ABSTELLEN": AreaType.STOREROOM,
    "ABSTELLRAUM": AreaType.STOREROOM,
    "WINTERGARTEN": AreaType.WINTERGARTEN,
    "SOGGIORNO": AreaType.LIVING_ROOM,
    "MIETERKELLER": AreaType.BASEMENT,
    "BUANDERIE": AreaType.WASH_AND_DRY_ROOM,
    "SALON": AreaType.LIVING_ROOM,
    "SALONE": AreaType.LIVING_ROOM,
    "SEJOUR": AreaType.LIVING_ROOM,
    "SÉJOUR": AreaType.LIVING_ROOM,
    "EINSTELLHALLE": AreaType.CARPARK,
    "CAVES": AreaType.BASEMENT_COMPARTMENT,
    "CAVE": AreaType.BASEMENT_COMPARTMENT,
    "BASTELN": AreaType.WORKSHOP,
    "ABST": AreaType.STOREROOM,
    "GALERIE": AreaType.ARCADE,
    "BASTELRAUM": AreaType.WORKSHOP,
    "ARCHIV": AreaType.ARCHIVE,
    **{area_type.name: area_type for area_type in AreaType},
}
