// ACTIONS project
export const FIT_SCREEN = 'FIT_SCREEN';
export const NEW_PROJECT = 'NEW_PROJECT';
export const LOAD_PROJECT = 'LOAD_PROJECT';
export const GET_PROJECT_PENDING = 'GET_PROJECT_PENDING';
export const GET_PROJECT_FULFILLED = 'GET_PROJECT_FULFILLED';
export const GET_PROJECT_REJECTED = 'GET_PROJECT_REJECTED';
export const SAVE_PROJECT_PENDING = 'SAVE_PROJECT_PENDING';
export const SAVE_PROJECT_FULFILLED = 'SAVE_PROJECT_FULFILLED';
export const SAVE_PROJECT_REJECTED = 'SAVE_PROJECT_REJECTED';
export const SELECT_TOOL_EDIT = 'SELECT_TOOL_EDIT';
export const UNSELECT_ALL = 'UNSELECT_ALL';
export const SET_PROPERTIES = 'SET_PROPERTIES';
export const ROTATE_SELECTED_DOORS = 'ROTATE_SELECTED_DOORS';
export const REMOVE = 'REMOVE';
export const UNDO = 'UNDO';
export const ROLLBACK = 'ROLLBACK';
export const SET_PROJECT_PROPERTIES = 'SET_PROJECT_PROPERTIES';
export const SET_SCALE_TOOL_PROPERTIES = 'SET_SCALE_TOOL_PROPERTIES';
export const ENABLE_SCALING = 'ENABLE_SCALING';
export const DISABLE_SCALING = 'DISABLE_SCALING';
export const REMOVE_SCALING_LINES = 'REMOVE_SCALING_LINES';
export const CLEAR_SCALE_DRAWING = 'CLEAR_SCALE_DRAWING';
export const SET_SCALE_RATIO = 'SET_SCALE_RATIO';
export const SET_PAPER_FORMAT = 'SET_PAPER_FORMAT';
export const SET_SCENE_PROPERTIES = 'SET_SCENE_PROPERTIES';
export const SET_PROJECT_HASH_CODE = 'SET_PROJECT_HASH_CODE';
export const INIT_CATALOG = 'INIT_CATALOG';
export const TOGGLE_CATALOG_TOOLBAR = 'TOGGLE_CATALOG_TOOLBAR';
export const TOGGLE_SNAP = 'TOGGLE_SNAP';
export const TOGGLE_SHOW_SNAP_ELEMENTS = 'TOGGLE_SHOW_SNAP_ELEMENTS';
export const THROW_ERROR = 'THROW_ERROR';
export const THROW_WARNING = 'THROW_WARNING';
export const COPY_PROPERTIES = 'COPY_PROPERTIES';
export const PASTE_PROPERTIES = 'PASTE_PROPERTIES';
export const PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY = 'PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY';
export const ALTERATE_STATE = 'ALTERATE_STATE';
export const SET_MODE = 'SET_MODE';
export const SET_SCENE_DIMENSIONS = 'SET_SCENE_DIMENSIONS';
export const SET_BACKGROUND_DIMENSIONS = 'SET_BACKGROUND_DIMENSIONS';
export const SET_BACKGROUND_ROTATION = 'SET_BACKGROUND_ROTATION';
export const SET_BACKGROUND_SHIFT = 'SET_BACKGROUND_SHIFT';
export const SET_SHOW_BACKGROUND_ONLY = 'SET_SHOW_BACKGROUND_ONLY';
export const BEGIN_ROTATING_BACKGROUND = 'BEGIN_ROTATING_BACKGROUND';
export const UPDATE_ROTATING_BACKGROUND = 'UPDATE_ROTATING_BACKGROUND';
export const END_ROTATING_BACKGROUND = 'END_ROTATING_BACKGROUND';
export const SET_VALIDATION_ERRORS = 'SET_VALIDATION_ERRORS';
export const SET_ANNOTATION_FINISHED = 'SET_ANNOTATION_FINISHED';
export const SET_MUST_IMPORT_ANNOTATIONS = 'SET_MUST_IMPORT_ANNOTATIONS';
export const SET_HIGHLIGHTED_ERROR = 'SET_HIGHLIGHTED_ERROR';
export const REMOVE_CIRCULAR_GUIDE = 'REMOVE_CIRCULAR_GUIDE';
export const REGENERATE_AREAS = 'REGENERATE_AREAS';
export const SET_SCALE_VALIDATED = 'SET_SCALE_VALIDATED';
export const SET_PLAN_INFO = 'SET_PLAN_INFO';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const SET_CTRL_KEY_ACTIVE = 'SET_CTRL_KEY_ACTIVE';

// ACTIONS viewer2D
export const SELECT_TOOL_ZOOM_IN = 'SELECT_TOOL_ZOOM_IN';
export const SELECT_TOOL_ZOOM_OUT = 'SELECT_TOOL_ZOOM_OUT';
export const SELECT_TOOL_PAN = 'SELECT_TOOL_PAN';
export const UPDATE_2D_CAMERA = 'UPDATE_2D_CAMERA';

//ACTIONS items
export const SELECT_TOOL_DRAWING_ITEM = 'SELECT_TOOL_DRAWING_ITEM';
export const UPDATE_DRAWING_ITEM = 'UPDATE_DRAWING_ITEM';
export const END_DRAWING_ITEM = 'END_DRAWING_ITEM';
export const BEGIN_DRAGGING_ITEM = 'BEGIN_DRAGGING_ITEM';
export const UPDATE_DRAGGING_ITEM = 'UPDATE_DRAGGING_ITEM';
export const END_DRAGGING_ITEM = 'END_DRAGGING_ITEM';
export const BEGIN_ROTATING_ITEM = 'BEGIN_ROTATING_ITEM';
export const UPDATE_ROTATING_ITEM = 'UPDATE_ROTATING_ITEM';
export const END_ROTATING_ITEM = 'END_ROTATING_ITEM';
export const INCREASE_WIDTH_SELECTED_ITEMS = 'INCREASE_WIDTH_SELECTED_ITEMS';
export const DECREASE_WIDTH_SELECTED_ITEMS = 'DECREASE_WIDTH_SELECTED_ITEMS';
export const INCREASE_LENGTH_SELECTED_ITEMS = 'INCREASE_LENGTH_SELECTED_ITEMS';
export const DECREASE_LENGTH_SELECTED_ITEMS = 'DECREASE_LENGTH_SELECTED_ITEMS';
export const COPY_SELECTED_ITEM = 'COPY_SELECTED_ITEM';

//ACTION drawings
export const SELECT_HOLE = 'SELECT_HOLE';
export const UNSELECT_HOLE = 'UNSELECT_HOLE';
export const SELECT_AREA = 'SELECT_AREA';
export const UNSELECT_AREA = 'UNSELECT_AREA';
export const SELECT_ITEM = 'SELECT_ITEM';
export const UNSELECT_ITEM = 'UNSELECT_ITEM';
export const SELECT_LINE = 'SELECT_LINE';
export const UNSELECT_LINE = 'UNSELECT_LINE';
export const SELECT_TOOL_DRAWING_LINE = 'SELECT_TOOL_DRAWING_LINE';
export const BEGIN_DRAWING_LINE = 'BEGIN_DRAWING_LINE';
export const UPDATE_DRAWING_LINE = 'UPDATE_DRAWING_LINE';
export const END_DRAWING_LINE = 'END_DRAWING_LINE';
export const SELECT_TOOL_DRAWING_HOLE = 'SELECT_TOOL_DRAWING_HOLE';
export const UPDATE_DRAWING_HOLE = 'UPDATE_DRAWING_HOLE'; //SHOULD BE SLPITTED IN BEGIN_DRAWING_HOLE AND UPDATE_DRAWING_HOLE
export const END_DRAWING_HOLE = 'END_DRAWING_HOLE';
export const SELECT_TOOL_UPLOAD_IMAGE = 'SELECT_TOOL_UPLOAD_IMAGE';
export const BEGIN_UPLOADING_IMAGE = 'BEGIN_UPLOADING_IMAGE';
export const END_UPLOADING_IMAGE = 'END_UPLOADING_IMAGE';
export const BEGIN_FITTING_IMAGE = 'BEGIN_FITTING_IMAGE';
export const END_FITTING_IMAGE = 'END_FITTING_IMAGE';
export const BEGIN_DRAGGING_HOLE = 'BEGIN_DRAGGING_HOLE';
export const UPDATE_DRAGGING_HOLE = 'UPDATE_DRAGGING_HOLE';
export const END_DRAGGING_HOLE = 'END_DRAGGING_HOLE';
export const INCREASE_WIDTH_SELECTED_WALLS = 'INCREASE_WIDTH_SELECTED_WALLS';
export const DECREASE_WIDTH_SELECTED_WALLS = 'DECREASE_WIDTH_SELECTED_WALLS';
export const CHANGE_REFERENCE_LINE = 'CHANGE_REFERENCE_LINE';
export const INCREASE_WIDTH_SELECTED_HOLES = 'INCREASE_WIDTH_SELECTED_HOLES';
export const DECREASE_WIDTH_SELECTED_HOLES = 'DECREASE_WIDTH_SELECTED_HOLES';
export const COPY_SELECTED_HOLE = 'COPY_SELECTED_HOLE';

export const CHANGE_LINE_TYPE = 'CHANGE_LINE_TYPE';
export const CHANGE_LINES_TYPE = 'CHANGE_LINES_TYPE';
export const CHANGE_HOLE_TYPE = 'CHANGE_HOLE_TYPE';
export const CHANGE_HOLES_TYPE = 'CHANGE_HOLES_TYPE';
export const CHANGE_ITEM_TYPE = 'CHANGE_ITEM_TYPE';
export const CHANGE_ITEMS_TYPE = 'CHANGE_ITEMS_TYPE';

// ACTION copy paste
export const BEGIN_COPY_PASTE_SELECTION = 'BEGIN_COPY_PASTE_SELECTION';
export const UPDATE_COPY_PASTE_SELECTION = 'UPDATE_COPY_PASTE_SELECTION';
export const END_COPY_PASTE_SELECTION = 'END_COPY_PASTE_SELECTION';

export const BEGIN_DRAGGING_COPY_PASTE_SELECTION = 'BEGIN_DRAGGING_COPY_PASTE_SELECTION';
export const UPDATE_DRAGGING_COPY_PASTE_SELECTION = 'UPDATE_DRAGGING_COPY_PASTE_SELECTION';
export const END_DRAGGING_COPY_PASTE_SELECTION = 'END_DRAGGING_COPY_PASTE_SELECTION';

export const SAVE_COPY_PASTE_SELECTION = 'SAVE_COPY_PASTE_SELECTION';
export const RESTORE_COPY_PASTE_FROM_ANOTHER_PLAN = 'RESTORE_COPY_PASTE_FROM_ANOTHER_PLAN';
export const BEGIN_ROTATING_COPY_PASTE_SELECTION = 'BEGIN_ROTATING_COPY_PASTE_SELECTION';
export const UPDATE_ROTATING_COPY_PASTE_SELECTION = 'UPDATE_ROTATING_COPY_PASTE_SELECTION';
export const END_ROTATING_COPY_PASTE_SELECTION = 'END_ROTATING_COPY_PASTE_SELECTION';

// ACTION rectangle tool
export const BEGIN_RECTANGLE_SELECTION = 'BEGIN_RECTANGLE_SELECTION';
export const UPDATE_RECTANGLE_SELECTION = 'UPDATE_RECTANGLE_SELECTION';
export const END_RECTANGLE_SELECTION = 'END_RECTANGLE_SELECTION';

//ACTIONS vertices
export const BEGIN_DRAGGING_VERTEX = 'BEGIN_DRAGGING_VERTEX';
export const UPDATE_DRAGGING_VERTEX = 'UPDATE_DRAGGING_VERTEX';
export const END_DRAGGING_VERTEX = 'END_DRAGGING_VERTEX';

//ACTIONS scene
export const SELECT_LAYER = 'SELECT_LAYER';

// Plan actions
export const FETCH_SITE_CLASSIFICATION_FULFILLED = 'FETCH_SITE_CLASSIFICATION_FULFILLED';
export const FETCH_SITE_CLASSIFICATION_REJECTED = 'FETCH_SITE_CLASSIFICATION_REJECTED';

export const FETCH_SITE_STRUCTURE_FULFILLED = 'FETCH_SITE_STRUCTURE_FULFILLED';
export const FETCH_SITE_STRUCTURE_REJECTED = 'FETCH_SITE_STRUCTURE_REJECTED';

export const FETCH_FLOOR_SCALES_FULFILLED = 'FETCH_FLOOR_SCALES_FULFILLED';
export const FETCH_FLOOR_SCALES_PENDING = 'FETCH_FLOOR_SCALES_PENDING';
export const SET_FLOORPLAN_DIMENSIONS = 'SET_FLOORPLAN_DIMENSIONS';

// Plan - Floor plan actions
export const FETCH_FLOORPLAN_PENDING = 'FETCH_FLOORPLAN_PENDING';
export const FETCH_FLOORPLAN_REJECTED = 'FETCH_FLOORPLAN_REJECTED';
export const FETCH_FLOORPLAN_FULFILLED = 'FETCH_FLOORPLAN_FULFILLED';

// Plan - Scale
export const SET_PLAN_SCALE = 'SET_PLAN_SCALE';

//GROUPING ACTIONS
export const PROJECT_ACTIONS = {
  FIT_SCREEN,
  REGENERATE_AREAS,
  NEW_PROJECT,
  LOAD_PROJECT,
  SAVE_PROJECT_PENDING,
  SAVE_PROJECT_FULFILLED,
  SAVE_PROJECT_REJECTED,
  GET_PROJECT_PENDING,
  GET_PROJECT_FULFILLED,
  GET_PROJECT_REJECTED,
  SELECT_TOOL_EDIT,
  UNSELECT_ALL,
  SET_PROPERTIES,
  REMOVE,
  UNDO,
  ROLLBACK,
  SET_PROJECT_PROPERTIES,
  ENABLE_SCALING,
  DISABLE_SCALING,
  REMOVE_SCALING_LINES,
  CLEAR_SCALE_DRAWING,
  SET_SCALE_TOOL_PROPERTIES,
  SET_SCALE_RATIO,
  SET_PAPER_FORMAT,
  SET_SCENE_PROPERTIES,
  SET_PROJECT_HASH_CODE,
  INIT_CATALOG,
  TOGGLE_CATALOG_TOOLBAR,
  TOGGLE_SNAP,
  TOGGLE_SHOW_SNAP_ELEMENTS,
  THROW_ERROR,
  THROW_WARNING,
  COPY_PROPERTIES,
  PASTE_PROPERTIES,
  PUSH_LAST_SELECTED_CATALOG_ELEMENT_TO_HISTORY,
  ALTERATE_STATE,
  SET_MODE,
  SET_SCENE_DIMENSIONS,
  SET_BACKGROUND_DIMENSIONS,
  SET_BACKGROUND_ROTATION,
  SET_BACKGROUND_SHIFT,
  SET_SHOW_BACKGROUND_ONLY,
  SET_VALIDATION_ERRORS,
  SET_ANNOTATION_FINISHED,
  SET_MUST_IMPORT_ANNOTATIONS,
  SET_HIGHLIGHTED_ERROR,
  SET_SCALE_VALIDATED,
  SET_PLAN_INFO,
  SHOW_SNACKBAR,
  CLOSE_SNACKBAR,
  SET_CTRL_KEY_ACTIVE,
};

export const VIEWER2D_ACTIONS = {
  SELECT_TOOL_ZOOM_IN,
  SELECT_TOOL_ZOOM_OUT,
  SELECT_TOOL_PAN,
  UPDATE_2D_CAMERA,
};

export const ITEMS_ACTIONS = {
  SELECT_ITEM,
  UNSELECT_ITEM,
  SELECT_TOOL_DRAWING_ITEM,
  UPDATE_DRAWING_ITEM,
  END_DRAWING_ITEM,
  BEGIN_DRAGGING_ITEM,
  UPDATE_DRAGGING_ITEM,
  END_DRAGGING_ITEM,
  BEGIN_ROTATING_ITEM,
  UPDATE_ROTATING_ITEM,
  END_ROTATING_ITEM,
  INCREASE_WIDTH_SELECTED_ITEMS,
  DECREASE_WIDTH_SELECTED_ITEMS,
  INCREASE_LENGTH_SELECTED_ITEMS,
  DECREASE_LENGTH_SELECTED_ITEMS,
  COPY_SELECTED_ITEM,
  CHANGE_ITEM_TYPE,
  CHANGE_ITEMS_TYPE,
};

export const HOLE_ACTIONS = {
  SELECT_HOLE,
  UNSELECT_HOLE,
  SELECT_TOOL_DRAWING_HOLE,
  UPDATE_DRAWING_HOLE,
  END_DRAWING_HOLE,
  BEGIN_DRAGGING_HOLE,
  UPDATE_DRAGGING_HOLE,
  END_DRAGGING_HOLE,
  ROTATE_SELECTED_DOORS,
  INCREASE_WIDTH_SELECTED_HOLES,
  DECREASE_WIDTH_SELECTED_HOLES,
  COPY_SELECTED_HOLE,
  CHANGE_HOLE_TYPE,
  CHANGE_HOLES_TYPE,
};

export const LINE_ACTIONS = {
  CHANGE_LINE_TYPE,
  CHANGE_LINES_TYPE,
  SELECT_LINE,
  UNSELECT_LINE,
  SELECT_TOOL_DRAWING_LINE,
  BEGIN_DRAWING_LINE,
  UPDATE_DRAWING_LINE,
  END_DRAWING_LINE,
  INCREASE_WIDTH_SELECTED_WALLS,
  DECREASE_WIDTH_SELECTED_WALLS,
  CHANGE_REFERENCE_LINE,
};

export const AREA_ACTIONS = {
  SELECT_AREA,
  UNSELECT_AREA,
};

export const SCENE_ACTIONS = {
  SELECT_LAYER,
};

export const VERTEX_ACTIONS = {
  BEGIN_DRAGGING_VERTEX,
  UPDATE_DRAGGING_VERTEX,
  END_DRAGGING_VERTEX,
};

export const PLAN_ACTIONS = {
  FETCH_FLOORPLAN_FULFILLED,
  FETCH_FLOORPLAN_PENDING,
  FETCH_FLOORPLAN_REJECTED,
  SET_PLAN_SCALE,
  SET_FLOORPLAN_DIMENSIONS,
  FETCH_SITE_CLASSIFICATION_FULFILLED,
  FETCH_SITE_STRUCTURE_FULFILLED,
  FETCH_SITE_STRUCTURE_REJECTED,
  FETCH_FLOOR_SCALES_FULFILLED,
  FETCH_FLOOR_SCALES_PENDING,
};

export const COPY_PASTE_ACTIONS = {
  BEGIN_COPY_PASTE_SELECTION,
  UPDATE_COPY_PASTE_SELECTION,
  END_COPY_PASTE_SELECTION,
  BEGIN_DRAGGING_COPY_PASTE_SELECTION,
  UPDATE_DRAGGING_COPY_PASTE_SELECTION,
  END_DRAGGING_COPY_PASTE_SELECTION,
  SAVE_COPY_PASTE_SELECTION,
  RESTORE_COPY_PASTE_FROM_ANOTHER_PLAN,
  BEGIN_ROTATING_COPY_PASTE_SELECTION,
  UPDATE_ROTATING_COPY_PASTE_SELECTION,
  END_ROTATING_COPY_PASTE_SELECTION,
};

export const RECTANGLE_TOOL_ACTIONS = {
  BEGIN_RECTANGLE_SELECTION,
  UPDATE_RECTANGLE_SELECTION,
  END_RECTANGLE_SELECTION,
};

//MODES
export const MODE_IDLE = 'MODE_IDLE';
export const MODE_RECTANGLE_TOOL = 'MODE_RECTANGLE_TOOL';
export const MODE_2D_ZOOM_IN = 'MODE_2D_ZOOM_IN';
export const MODE_2D_ZOOM_OUT = 'MODE_2D_ZOOM_OUT';
export const MODE_2D_PAN = 'MODE_2D_PAN';
export const MODE_WAITING_DRAWING_LINE = 'MODE_WAITING_DRAWING_LINE';
export const MODE_DRAGGING_VERTEX = 'MODE_DRAGGING_VERTEX';
export const MODE_DRAGGING_ITEM = 'MODE_DRAGGING_ITEM';
export const MODE_DRAGGING_HOLE = 'MODE_DRAGGING_HOLE';
export const MODE_DRAWING_LINE = 'MODE_DRAWING_LINE';
export const MODE_DRAWING_HOLE = 'MODE_DRAWING_HOLE';
export const MODE_DRAWING_ITEM = 'MODE_DRAWING_ITEM';
export const MODE_ROTATING_ITEM = 'MODE_ROTATING_ITEM';
export const MODE_UPLOADING_IMAGE = 'MODE_UPLOADING_IMAGE';
export const MODE_FITTING_IMAGE = 'MODE_FITTING_IMAGE';
export const MODE_COPY_PASTE = 'MODE_COPY_PASTE';
export const MODE_ROTATE_SCALE_BACKGROUND = 'MODE_ROTATE_SCALE_BACKGROUND';
export const MODE_IMPORT_ANNOTATIONS = 'MODE_IMPORT_ANNOTATIONS';
export const MODE_HELP = 'MODE_HELP';
export const MODE_CONFIGURING_PROJECT = 'MODE_CONFIGURING_PROJECT';

export const MODE_SNAPPING = [
  MODE_IDLE,
  MODE_2D_ZOOM_IN,
  MODE_2D_ZOOM_OUT,
  MODE_2D_PAN,
  MODE_WAITING_DRAWING_LINE,
  MODE_DRAWING_LINE,
  MODE_DRAWING_HOLE,
  MODE_DRAWING_ITEM,
  MODE_DRAGGING_VERTEX,
  MODE_DRAGGING_ITEM,
  MODE_DRAGGING_HOLE,
  MODE_FITTING_IMAGE,
  MODE_UPLOADING_IMAGE,
  MODE_ROTATING_ITEM,
];

//UNITS
export const UNIT_MILLIMETER = 'mm';
export const UNIT_CENTIMETER = 'cm';
export const UNIT_METER = 'm';
export const UNIT_INCH = 'in';
export const UNIT_FOOT = 'ft';
export const UNIT_MILE = 'mi';

export const UNITS_LENGTH = [UNIT_MILLIMETER, UNIT_CENTIMETER, UNIT_METER, UNIT_INCH, UNIT_FOOT, UNIT_MILE];

export const EPSILON = 1e-8;
export const BUFFER_RADIUS_KM = 1e-5; // 1 cm

export const KEYBOARD_KEYS = {
  DELETE: 'Delete',
  BACKSPACE: 'Backspace',
  ENTER: 'Enter',
  TAB: 'Tab',
  ESCAPE: 'Escape',
  Z: 'z',
  X: 'x',
  R: 'r',
  L: 'l',
  F: 'f',
  S: 's',
  PLUS: '+',
  MINUS: '-',
  CTRL: 'Control',
  SPACE: ' ',
  ARROW_UP: 'ArrowUp',
  ARROW_DOWN: 'ArrowDown',
  ARROW_LEFT: 'ArrowLeft',
  ARROW_RIGHT: 'ArrowRight',
  C: 'c',
  V: 'v',
};

export const COLORS = {
  PRIMARY_COLOR: '#2a79a1',
  STROKE_NON_SELECTED_ITEM: '#2b2b2b',
  INVALID: '#ff0000', // red
  VALID: '#00ff00', // green
  WHITE: '#ffffff',
  TRANSPARENT: 'transparent',
  CATALOG: {
    // Extracted from old editor and converted to hex: https://github.com/Archilyse/slam/blob/develop/ui/pipeline/src/app/editor/config.ts
    AREA_SPLITTER: '#000000',
    SCALE_TOOL: '#008000',
    BATHTUB: '#ff00ff',
    BIKE_PARKING: '#c0eaff',
    BUILT_IN_FURNITURE: '#ffc0cb',
    CAR_PARKING: '#739de2',
    COLUMN: '#800000',
    DOOR: '#00ff00',
    ELEVATOR: '#493400',
    ENTRANCE_DOOR: '#000000', // We use a different one than in the old editor so is not confused with the selected color
    KITCHEN: '#ffff00',
    RAILINGS: '#800080',
    OFFICE_DESK: '#62a8a8',
    RAMP: '#9fa3a0',
    SEAT: '#ffc0cb',
    SHAFT: '#7d7d7d',
    SHOWER: '#c07e18',
    SINK: '#008000',
    STAIRS: '#91d17e',
    TABLE: '#ffc0cb',
    TOILET: '#00ffff',
    WALL: '#2a79a1',
    WASHING_MACHINE: '#ffc0cb',
    WINDOW: '#ff0000',
    DEFAULT: '#84e1ce',
  },
  SELECTED_ELEMENT: '#0096fd',
  TOOLBAR_ACTIVE_ICON: '#1ca6fc',
};

// Used in an enum property that only accepts strings for possible values
export const ITEM_DIRECTION = {
  UP: '1',
  DOWN: '-1',
};

export const REFERENCE_LINE_POSITION = {
  OUTSIDE_FACE: 'OUTSIDE_FACE',
  INSIDE_FACE: 'INSIDE_FACE',
  CENTER: 'CENTER',
} as const;

export const OPENING_NAME = {
  DOOR: 'Door',
  ENTRANCE_DOOR: 'Entrance Door',
  SLIDING_DOOR: 'Sliding Door',
  WINDOW: 'Window',
};

export const OPENING_TYPE = {
  DOOR: 'door',
  ENTRANCE_DOOR: 'entrance_door',
  SLIDING_DOOR: 'sliding_door',
  WINDOW: 'window',
} as const;

export const CATALOG_ELEMENT_OPACITY = 0.65;
export const CATALOG_ELEMENT_OPACITY_SELECTED = 0.85;
export const VERTEX_ROUNDING_PRECISION = 12; // Same as in BE
export const VERTEX_SCALING_OPACITY = 0;
export const VERTEX_DEFAULT_OPACITY = 1;
export const COOKIES = {
  AUTH_TOKEN: 'access_token',
  ROLES: 'roles',
};

export const ROLES = {
  ADMIN: 'ADMIN',
  TEAMMEMBER: 'TEAMMEMBER',
  TEAMLEADER: 'TEAMLEADER',
};
export const ENDPOINTS = {
  LOGIN: () => '/auth/login',
  ANNOTATION_PLAN: (planId, { validated } = { validated: true }) =>
    validated ? `/annotation/v2/plan/${planId}?validated=true` : `/annotation/v2/plan/${planId}`,
  FLOORPLAN_IMG_PLAN: planId => `/plan/${planId}/raw_image`,
  PLAN_BY_ID: planId => `/plan/${planId}`,
  CLASSIFICATION_SCHEME: schemeName => `/constants/classification_schemes/${schemeName}`,
  SITE_STRUCTURE: siteId => `/site/${siteId}/structure`,
  SITE_BY_ID: siteId => `/site/${siteId}`,
  PLAN_HEIGHTS: planId => `/plan/${planId}/heights`,
  CREATE_AREA_SPLITTERS: planId => `/plan/${planId}/area_splitters`,
};

export const URLS = {
  HOME: () => '/',
  LOGIN: () => '/login',
  OLD_PIPELINE_CLASSIFICATION: planId => `/classification/${planId}`,
};

export const SERVER_BASENAME = 'v2/editor';

export const RequestStatusType = {
  IDLE: 'IDLE',
  PENDING: 'PENDING',
  FULFILLED: 'FULFILLED',
  REJECTED: 'REJECTED',
} as const;

export const REQUEST_STATUS_BY_ACTION = {
  FETCH_FLOOR_SCALES: 'FETCH_FLOOR_SCALES',
  GET_PLAN_ANNOTATIONS: 'GET_PLAN_ANNOTATIONS',
  SAVE_PLAN_ANNOTATIONS: 'SAVE_PLAN_ANNOTATIONS',
} as const;

export const CIRCLE_RADIUS = '3';
export const CIRCLE_RADIUS_REFERENCE = '4';

const range = (start: number, end: number): number[] => Array.from({ length: end - start }, (v, k) => k + start);
export const POSSIBLE_WALL_WIDTHS = range(5, 91);

export const SNAPS = {
  COPY_PASTE: {
    POINT: {
      RADIUS: 30,
    },
    SEGMENT: {
      RADIUS: 25,
    },
  },
  POINT: {
    RADIUS: 10,
    PRIORITY: 10,
  },
  SEGMENT: {
    RADIUS: 5,
    PRIORITY: 1,
  },
  PERP_SEGMENT: {
    RADIUS: 3,
    PRIORITY: 5,
  },
  ITEM: {
    RADIUS: 10,
    PRIORITY: 5,
    AREAS_PRIORITY: 3,
  },
};

export const SeparatorsType = {
  WALL: 'wall',
  RAILING: 'railing',
  COLUMN: 'column',
  AREA_SPLITTER: 'area_splitter',
  SCALE_TOOL: 'scale_tool',
} as const;

export const MIN_HOLE_LENGTH = 25;
export const MIN_ITEM_WIDTH = 10;
export const MIN_ITEM_LENGTH = 10;

export const MIN_WALL_LENGTH_IN_CM = 4;

export const ITEM_STROKE_WIDTH = 1;

export const INITIAL_SCENE_WIDTH = 3000;
export const INITIAL_SCENE_HEIGHT = 2000;

export const INITIAL_BACKGROUND_WIDTH = INITIAL_SCENE_WIDTH;
export const INITIAL_BACKGROUND_HEIGHT = INITIAL_SCENE_HEIGHT;
export const INITIAL_BACKGROUND_ROTATION = 0;

export const PrototypesEnum = {
  AREAS: 'areas',
  ITEMS: 'items',
  HOLES: 'holes',
  LINES: 'lines',
  VERTICES: 'vertices',
} as const;

export const MAX_HISTORY_LIST_SIZE = 10;

export const MEASURE_STEP_ITEM = 1;
export const MEASURE_STEP_HOLE = 5;
export const MEASURE_STEP_FALLBACK = 1;

export const SNACKBAR_DURATION_FOREVER = null;

export const STORAGE = {
  COPY_PASTE: 'copy_paste',
};
export const GEOJSON_FEATURE_TYPES = {
  POLYGON: 'Polygon',
  MULTIPOLYGON: 'MultiPolygon',
};

export const ACCEPTED_NUMBER_OF_COORDINATES = 5;
export const ACCEPTED_NUMBER_OF_POLYGON_EDGES = 4;

export const SCALING_REQUIRED_MEASUREMENT_COUNT = 2;
export const SCALING_MAX_DIFF_BETWEEN_MEASUREMENTS = 1; // 1 cm
export const SCALING_BASELINE = 100; // 100 px

export const RESCALE_NOT_ALLOWED_MESSAGE = 'Cannot re-scale in a plan with annotations';

// Sizes in Centimeters
export const PAGE_SIZES = {
  A0: { width: 118.9, height: 84.1 },
  A1: { width: 84.1, height: 59.4 },
  A2: { width: 59.4, height: 42 },
  A3: { width: 42, height: 29.7 },
  A4: { width: 29, height: 21 },
  A5: { width: 21, height: 14.8 },
  A6: { width: 14.8, height: 10.5 },
  A7: { width: 10.5, height: 7.4 },
  A8: { width: 7.4, height: 5.2 },
  A9: { width: 5.2, height: 3.7 },
  A10: { width: 3.7, height: 2.6 },
};
export const SVG_PLAN_CLASSNAME = 'svg-plan';

export const DEFAULT_WALL_WIDTH = 20;
export const DEFAULT_AREA_SPLITTER_WIDTH = 1;

export enum METRICS_EVENTS {
  DRAWING_LINE = 'drawing-line',
  DRAWING_OPENING = 'drawing-opening',
  DRAWING_ITEM = 'drawing-item',
}
